def exportJSON_LD(phones):
    # file = open("website/static/export/phones.json")
    file = open("phones.jsonld", mode='w')
    for phone in phones:
        print("<script type=\"application/ld+json\">", file=file)
        print("{", file=file)
        print("\t\"@context\": \"https://schema.org\",", file=file)
        print("\t\"@type\": \"Product\",", file=file)
        print("\t\"category\": \"MobilePhone\",", file=file)
        print("\t\"name\": \"%s\"," % (phone[1]), file=file)
        print("\t\"offers\": {", file=file)
        print("\t\t\"@type\": \"Offer\",", file=file)
        print("\t\t\"price\": \"%.2f\"," % (phone[2]), file=file)
        print("\t\t\"priceCurrency\": \"CNY\"", file=file)
        print("\t},", file=file)
        print("\t\"size\": \"%.2f inch\"," % (phone[4]), file=file)
        print("\t\"image\": \"%s\"," % (phone[14]), file=file)
        print("\t\"brand\": {", file=file)
        print("\t\t\"@type\": \"Brand\",", file=file)
        print("\t\t\"name\": \"%s\"" % (phone[15]), file=file)
        print("\t},", file=file)
        print("\t\"additionalProperty\": [", file=file)
        print("\t\t{", file=file)
        print("\t\t\t\"@type\": \"PropertyValue\",", file=file)
        print("\t\t\t\"name\": \"System Kernel\",", file=file)
        print("\t\t\t\"value\": \"%s\"" % (phone[3]), file=file)
        print("\t\t},", file=file)
        print("\t\t{", file=file)
        print("\t\t\t\"@type\": \"PropertyValue\",", file=file)
        print("\t\t\t\"name\": \"Operating System\",", file=file)
        print("\t\t\t\"value\": \"%s\"" % (phone[5]), file=file)
        print("\t\t},", file=file)
        print("\t\t{", file=file)
        print("\t\t\t\"@type\": \"PropertyValue\",", file=file)
        print("\t\t\t\"name\": \"Resolution\",", file=file)
        print("\t\t\t\"value\": \"%s\"" % (phone[6]), file=file)
        print("\t\t},", file=file)
        print("\t\t{", file=file)
        print("\t\t\t\"@type\": \"PropertyValue\",", file=file)
        print("\t\t\t\"name\": \"Processor frequency\",", file=file)
        print("\t\t\t\"value\": \"%.2f\"" % (phone[7]), file=file)
        print("\t\t},", file=file)
        print("\t\t{", file=file)
        print("\t\t\t\"@type\": \"PropertyValue\",", file=file)
        print("\t\t\t\"name\": \"Kernel number\",", file=file)
        print("\t\t\t\"value\": \"%d\"" % (phone[8]), file=file)
        print("\t\t},", file=file)
        print("\t\t{", file=file)
        print("\t\t\t\"@type\": \"PropertyValue\",", file=file)
        print("\t\t\t\"name\": \"RAM capacity\",", file=file)
        print("\t\t\t\"value\": \"%d\"" % (phone[9]), file=file)
        print("\t\t},", file=file)
        print("\t\t{", file=file)
        print("\t\t\t\"@type\": \"PropertyValue\",", file=file)
        print("\t\t\t\"name\": \"ROM capacity\",", file=file)
        print("\t\t\t\"value\": \"%d GB\"" % (phone[10]), file=file)
        print("\t\t},", file=file)
        print("\t\t{", file=file)
        print("\t\t\t\"@type\": \"PropertyValue\",", file=file)
        print("\t\t\t\"name\": \"Battery capacity\",", file=file)
        print("\t\t\t\"value\": \"%d mAh\"" % (phone[11]), file=file)
        print("\t\t},", file=file)
        print("\t\t{", file=file)
        print("\t\t\t\"@type\": \"PropertyValue\",", file=file)
        print("\t\t\t\"name\": \"Rear camera pixels\",", file=file)
        print("\t\t\t\"value\": \"%d megapixel\"" % (phone[12]), file=file)
        print("\t\t},", file=file)
        print("\t\t{", file=file)
        print("\t\t\t\"@type\": \"PropertyValue\",", file=file)
        print("\t\t\t\"name\": \"Front camera pixels\",", file=file)
        print("\t\t\t\"value\": \"%d megapixel\"" % (phone[13]), file=file)
        print("\t\t},", file=file)
        print("\t\t{", file=file)
        print("\t\t\t\"@type\": \"PropertyValue\",", file=file)
        print("\t\t\t\"name\": \"Usage\",", file=file)
        print("\t\t\t\"value\": \"%s\"" % (phone[16]), file=file)
        print("\t\t}", file=file)
        print("\t]", file=file)
        print("}", file=file)
        print("</script>", file=file)
    file.close()


def exportXML(phones):
    # file = open("website/static/export/phones.xml")
    file = open("phones.xml")


phones = [[1, 'OPPO A32(8GB/128GB/ All Netcom )', 1499, 'Android', 6.5, 'Color', '720P', 1.8, 8, 8, 128, 5000, 13, 8,
           'https://pro-fd.zol-img.com.cn/t_s300x300c5/g6/M00/02/01/ChMkKV9Z_KeIBXZUAAC-BeJRWEUAACIDwEB6AoAAL4d919.jpg',
           'OPPO', 'Business'],
          [1, 'Redmi 8A(3GB/32GB/ All Netcom )', 599, 'MIUI', 6.22, 'MIUI', '720P', 2, 8, 3, 32, 5000, 12, 8,
           'https://pro-fd.zol-img.com.cn/t_s300x300c5/g1/M09/00/08/ChMljV2kSqWIUHBLAACcAbMG0LMAAP92QKihe4AAJwZ139.jpg',
           'Redmi', 'Business']]
exportJSON_LD(phones)
