def exportJSON(phones):
    # file = open("website/static/export/phones.json")
    file = open("phones.json")
    print("[", file=file)
    for phone in phones:
        print("\t{", file=file)
        print("\t\t\"@context\": \"https://schema.org\",", file=file)
        print("\t\t\"@type\": \"Product\",", file=file)
        print("\t\t\"category\": \"MobilePhone\",", file=file)
        print("\t\t\"name\": \"%s\"," % (phone[0]), file=file)
        print("\t\t\"price\": %f.2," % (phone[1]), file=file)
        print("\t\t\"subjectOf\":", file=file)
        print("\t\t\t{:", file=file)
        print("\t\t\t\t\"@type\": \"SoftwareApplication\",", file=file)
        print("\t\t\t\t\"operatingSystem\": \"%s - %s\"" % (phone[2], phone[4]), file=file)
        print("\t\t\t}:", file=file)
        print("\t\t\"size\": %f.2," % (phone[3]), file=file)
        print("\t\t\"@type\": \"Product\",", file=file)
        print("\t\t\"@type\": \"Product\",", file=file)
        print("\t\t\"@type\": \"Product\",", file=file)
        print("\t\t\"@type\": \"Product\",", file=file)
        print("\t\t\"@type\": \"Product\",", file=file)
        print("\t\t\"@type\": \"Product\",", file=file)
        print("\t\t\"@type\": \"Product\",", file=file)
        print("\t\t\"@type\": \"Product\",", file=file)
        print("\t\t\"@type\": \"Product\",", file=file)
        print("\t\t\"@type\": \"Product\",", file=file)
        print("\t\t\"@type\": \"Product\",", file=file)
        print("\t\t\"@type\": \"Product\",", file=file)
        print("\t}", file=file)
    print("]", file=file)

def exportXML(phones):
    # file = open("website/static/export/phones.xml")
    file = open("phones.xml")